INSERT INTO "public"."pbq_exercises" ("id", "exam", "type", "domain", "title", "question", "explanation", "payload") VALUES ('1', 'core1', 'bucket', 'Networking', 'OSI Model Classification', 'Classify each protocol, device, or technology into its correct OSI model layer. Click an item from the pool, then click the target layer to place it.', 'Layer 7 (Application) — user-facing protocols like HTTP, FTP, SMTP, DNS.
Layer 6 (Presentation) — data formatting, encryption, compression: SSL/TLS.
Layer 5 (Session) — establishes/manages sessions: NetBIOS.
Layer 4 (Transport) — end-to-end delivery: TCP (reliable) and UDP (best-effort).
Layer 3 (Network) — logical addressing and routing: IP, ICMP, Router.
Layer 2 (Data Link) — MAC addressing and framing: Ethernet, ARP, Switch.
Layer 1 (Physical) — raw bits over a medium: Hub, Repeater, copper/fiber cable.', '{"items":[{"id":"http","label":"HTTP / HTTPS","bucket":7},{"id":"ftp","label":"FTP","bucket":7},{"id":"smtp","label":"SMTP","bucket":7},{"id":"dns","label":"DNS","bucket":7},{"id":"ssl","label":"SSL / TLS","bucket":6},{"id":"netbios","label":"NetBIOS","bucket":5},{"id":"tcp","label":"TCP","bucket":4},{"id":"udp","label":"UDP","bucket":4},{"id":"ip","label":"IPv4 / IPv6","bucket":3},{"id":"icmp","label":"ICMP","bucket":3},{"id":"router","label":"Router","bucket":3},{"id":"arp","label":"ARP","bucket":2},{"id":"ethernet","label":"Ethernet (MAC)","bucket":2},{"id":"switch","label":"Switch","bucket":2},{"id":"hub","label":"Hub / Repeater","bucket":1},{"id":"cable","label":"Copper / Fiber","bucket":1}],"buckets":[{"id":7,"label":"Layer 7","sublabel":"Application"},{"id":6,"label":"Layer 6","sublabel":"Presentation"},{"id":5,"label":"Layer 5","sublabel":"Session"},{"id":4,"label":"Layer 4","sublabel":"Transport"},{"id":3,"label":"Layer 3","sublabel":"Network"},{"id":2,"label":"Layer 2","sublabel":"Data Link"},{"id":1,"label":"Layer 1","sublabel":"Physical"}]}'), ('10', 'core1', 'bucket', 'Hardware', 'Modern CPU Features Classification', 'Classify each processor feature or characteristic into the correct CPU architecture or feature category.', 'x86-64 (AMD64/Intel 64) — the dominant desktop/server architecture; CISC-based; runs all legacy Windows software natively.
ARM64 (AArch64) — RISC-based; used in Apple Silicon (M-series), Qualcomm Snapdragon X, mobile SoCs; low power, high efficiency.
NPU / AI Acceleration — dedicated neural processing units for ML inference; required for Copilot+ PC (40+ TOPS); found in Intel Core Ultra, AMD Ryzen AI, Apple M-series, Snapdragon X.
PCIe & Platform — CPU-level connectivity specs: PCIe lanes, integrated memory controllers, chipset communication.', '{"items":[{"id":"intel-cisc","label":"Intel Core Ultra (CISC, x64 native)","bucket":"x86"},{"id":"amd-cisc","label":"AMD Ryzen (x64, backward compatible)","bucket":"x86"},{"id":"legacy-win","label":"Runs all legacy Windows 64-bit apps natively","bucket":"x86"},{"id":"apple-m","label":"Apple M-series (macOS/iOS)","bucket":"arm"},{"id":"snapdragon","label":"Qualcomm Snapdragon X Elite","bucket":"arm"},{"id":"arm-emul","label":"Runs x64 via emulation on Windows","bucket":"arm"},{"id":"copilot-req","label":"40+ TOPS required for Copilot+ PC","bucket":"npu"},{"id":"local-ai","label":"Enables local AI (no cloud) features","bucket":"npu"},{"id":"studio-fx","label":"Windows Studio Effects processing","bucket":"npu"},{"id":"pcie5","label":"PCIe 5.0 lanes (x16 = 64 GB/s)","bucket":"pcie"},{"id":"pcie4","label":"PCIe 4.0 NVMe M.2 slot","bucket":"pcie"}],"buckets":[{"id":"x86","label":"x86-64","sublabel":"CISC · Desktop/Server"},{"id":"arm","label":"ARM64","sublabel":"RISC · Mobile/Efficient"},{"id":"npu","label":"NPU / AI","sublabel":"ML Inference"},{"id":"pcie","label":"PCIe Platform","sublabel":"Connectivity"}]}'), ('2', 'core1', 'match', 'Networking', 'Wireless 802.11 Standards', 'Match each 802.11 wireless standard to its maximum theoretical speed and frequency band. Click a standard on the left, then click its spec on the right.', '802.11a — 54 Mbps, 5 GHz only (less interference, shorter range).
802.11b — 11 Mbps, 2.4 GHz (first consumer standard, slowest).
802.11g — 54 Mbps, 2.4 GHz (backward compatible with b).
802.11n (Wi-Fi 4) — up to 600 Mbps, dual-band 2.4/5 GHz, introduced MIMO.
802.11ac (Wi-Fi 5) — up to 3.5 Gbps, 5 GHz only, MU-MIMO, beamforming.
802.11ax (Wi-Fi 6/6E) — up to 9.6 Gbps, 2.4/5/6 GHz, OFDMA for dense environments.', '{"left":[{"id":"a","label":"802.11a"},{"id":"b","label":"802.11b"},{"id":"g","label":"802.11g"},{"id":"n","label":"802.11n  (Wi-Fi 4)"},{"id":"ac","label":"802.11ac (Wi-Fi 5)"},{"id":"ax","label":"802.11ax (Wi-Fi 6)"}],"right":[{"id":"a","label":"54 Mbps · 5 GHz"},{"id":"b","label":"11 Mbps · 2.4 GHz"},{"id":"g","label":"54 Mbps · 2.4 GHz"},{"id":"n","label":"600 Mbps · 2.4 / 5 GHz"},{"id":"ac","label":"3.5 Gbps · 5 GHz"},{"id":"ax","label":"9.6 Gbps · 2.4 / 5 / 6 GHz"}]}'), ('3', 'core1', 'bucket', 'Virtualization & Cloud', 'Cloud Service Models', 'Classify each product or service into the correct cloud service model (IaaS, PaaS, or SaaS). Click an item, then click the target category.', 'IaaS (Infrastructure as a Service) — you manage the OS and up; provider manages hardware. Examples: AWS EC2, Azure VMs, bare-metal cloud servers.
PaaS (Platform as a Service) — you deploy code/apps; provider manages OS, runtime, scaling. Examples: Google App Engine, Heroku, Azure App Service.
SaaS (Software as a Service) — you just use the application; provider manages everything. Examples: Microsoft 365, Gmail, Salesforce, Dropbox.', '{"items":[{"id":"ec2","label":"AWS EC2 (virtual machines)","bucket":"iaas"},{"id":"azurevm","label":"Azure Virtual Machines","bucket":"iaas"},{"id":"vnet","label":"Virtual networking / VPC","bucket":"iaas"},{"id":"gae","label":"Google App Engine","bucket":"paas"},{"id":"heroku","label":"Heroku","bucket":"paas"},{"id":"azuresql","label":"Azure SQL Database (managed)","bucket":"paas"},{"id":"office365","label":"Microsoft 365","bucket":"saas"},{"id":"gmail","label":"Gmail / Google Workspace","bucket":"saas"},{"id":"salesforce","label":"Salesforce CRM","bucket":"saas"},{"id":"dropbox","label":"Dropbox","bucket":"saas"}],"buckets":[{"id":"iaas","label":"IaaS","sublabel":"Infrastructure as a Service"},{"id":"paas","label":"PaaS","sublabel":"Platform as a Service"},{"id":"saas","label":"SaaS","sublabel":"Software as a Service"}]}'), ('4', 'core1', 'order', 'Troubleshooting', 'CompTIA Troubleshooting Methodology', 'Drag the steps into the correct order following the CompTIA A+ six-step troubleshooting methodology.', 'The CompTIA A+ troubleshooting methodology (in order):
1. Identify the problem — gather information, question the user, identify symptoms.
2. Establish a theory of probable cause — consider multiple causes (don''t overlook the obvious).
3. Test the theory to determine cause — confirm or deny the theory; escalate if needed.
4. Establish a plan of action — determine how to resolve the problem and any side effects.
5. Implement the solution or escalate — apply the fix or escalate if beyond scope.
6. Verify full system functionality — confirm the fix worked and prevent recurrence.
7. Document findings, actions, and outcomes — record everything for future reference.', '{"items":[{"id":1,"label":"Identify the problem"},{"id":2,"label":"Establish a theory of probable cause"},{"id":3,"label":"Test the theory to determine cause"},{"id":4,"label":"Establish a plan of action to resolve the problem"},{"id":5,"label":"Implement the solution or escalate"},{"id":6,"label":"Verify full system functionality"},{"id":7,"label":"Document findings, actions, and outcomes"}]}'), ('5', 'core1', 'match', 'Networking / Hardware', 'Network Cable Types', 'Match each cable type to its key characteristic or primary use case.', 'Cat 5e — Gigabit (1 Gbps) up to 100 m, most common budget LAN cable.
Cat 6 — 10 Gbps up to 55 m, better crosstalk rejection than Cat 5e.
Cat 6a — 10 Gbps up to 100 m (augmented), shielded, used in data centers.
Single-mode fiber — long-distance WAN/campus links, single light path, yellow jacket.
Multi-mode fiber — short-distance datacenter links, multiple light paths, orange or aqua jacket.
Coaxial (RG-6) — cable TV and broadband internet distribution to homes.', '{"left":[{"id":"cat5e","label":"Cat 5e"},{"id":"cat6","label":"Cat 6"},{"id":"cat6a","label":"Cat 6a"},{"id":"smf","label":"Single-mode fiber"},{"id":"mmf","label":"Multi-mode fiber"},{"id":"coax","label":"Coaxial (RG-6)"}],"right":[{"id":"cat5e","label":"1 Gbps up to 100 m · budget LAN runs"},{"id":"cat6","label":"10 Gbps up to 55 m · improved crosstalk rejection"},{"id":"cat6a","label":"10 Gbps up to 100 m · shielded, augmented"},{"id":"smf","label":"Long-distance links · single light path · yellow jacket"},{"id":"mmf","label":"Short datacenter links · multiple light paths · orange/aqua"},{"id":"coax","label":"Cable TV / broadband internet to homes"}]}'), ('6', 'core1', 'match', 'Hardware', 'Storage Interfaces & Technologies', 'Match each storage interface or technology to its defining characteristic.', 'NVMe — uses PCIe bus, up to ~7 GB/s on Gen 4, lowest latency — fastest consumer SSD protocol.
SATA III — 6 Gb/s (~600 MB/s) max, most common interface for 2.5" and 3.5" drives.
SAS (Serial Attached SCSI) — enterprise drives, up to 24 Gb/s, hot-swappable, high reliability.
M.2 — a form factor (slot), not a protocol; supports both SATA and NVMe drives.
iSCSI — block-level storage over TCP/IP, used for SANs across existing network infrastructure.
eMMC — soldered NAND flash chip, slower than NVMe/SATA SSD, found in budget tablets and phones.', '{"left":[{"id":"nvme","label":"NVMe"},{"id":"sata3","label":"SATA III"},{"id":"sas","label":"SAS"},{"id":"m2","label":"M.2"},{"id":"iscsi","label":"iSCSI"},{"id":"emmc","label":"eMMC"}],"right":[{"id":"nvme","label":"PCIe bus · up to ~7 GB/s · lowest-latency SSD protocol"},{"id":"sata3","label":"6 Gb/s max · most common desktop/laptop drive interface"},{"id":"sas","label":"Enterprise drives · up to 24 Gb/s · hot-swappable"},{"id":"m2","label":"Form factor only · supports both SATA and NVMe"},{"id":"iscsi","label":"Block-level storage over TCP/IP · SAN protocol"},{"id":"emmc","label":"Soldered NAND flash · used in budget tablets and phones"}]}'), ('7', 'core1', 'match', 'Hardware', 'Connector Types', 'Match each connector to its primary use case or device type.', 'RJ-45 — 8-pin modular connector used for Ethernet (networking).
RJ-11 — 6-pin modular connector used for telephone/DSL lines.
LC — small form-factor fiber optic connector, common in data centers.
SC — square push-pull fiber optic connector, older enterprise use.
ST — bayonet-style fiber optic connector, older campus networks.
F-type — threaded coaxial connector for cable TV and broadband modems.
DB-9 (RS-232) — legacy serial port for COM devices and console connections.', '{"left":[{"id":"rj45","label":"RJ-45"},{"id":"rj11","label":"RJ-11"},{"id":"lc","label":"LC"},{"id":"sc","label":"SC"},{"id":"st","label":"ST"},{"id":"ftype","label":"F-type"},{"id":"db9","label":"DB-9 (RS-232)"}],"right":[{"id":"rj45","label":"Ethernet networking (8 pins)"},{"id":"rj11","label":"Telephone / DSL lines (6 pins)"},{"id":"lc","label":"Small form-factor fiber · data centers"},{"id":"sc","label":"Square push-pull fiber · older enterprise"},{"id":"st","label":"Bayonet fiber · older campus networks"},{"id":"ftype","label":"Coaxial · cable TV and broadband modems"},{"id":"db9","label":"Legacy serial / COM port connections"}]}'), ('8', 'core1', 'bucket', 'Hardware', 'Printer Technology Classification', 'Classify each characteristic or component into the correct printer technology type.', 'Laser — uses a photosensitive drum, toner (powder), and a fuser to bond toner to paper with heat. Fast, high-volume, low per-page cost. The fuser assembly is a common failure point.
Inkjet — sprays liquid ink through microscopic nozzles. Better photo quality, lower upfront cost, but higher per-page cost and ink can dry out.
Thermal — uses heat-sensitive paper (direct thermal) or a thermal ribbon (thermal transfer). No ink/toner; common for receipts and shipping labels.
Impact (Dot Matrix) — a print head physically strikes an inked ribbon against paper. Loud, slow, but can print multi-part carbon forms.', '{"items":[{"id":"toner","label":"Uses toner (powder)","bucket":"laser"},{"id":"drum","label":"Photosensitive drum","bucket":"laser"},{"id":"fuser","label":"Fuser assembly (heat bonding)","bucket":"laser"},{"id":"liquidink","label":"Liquid ink cartridges","bucket":"inkjet"},{"id":"nozzle","label":"Microscopic nozzles / printheads","bucket":"inkjet"},{"id":"clog","label":"Nozzle clog — common maintenance issue","bucket":"inkjet"},{"id":"heatsens","label":"Heat-sensitive paper (no ink/toner)","bucket":"thermal"},{"id":"receipt","label":"Receipts and shipping labels","bucket":"thermal"},{"id":"ribbon","label":"Inked ribbon struck by print head","bucket":"impact"},{"id":"carbon","label":"Prints multi-part carbon forms","bucket":"impact"}],"buckets":[{"id":"laser","label":"Laser","sublabel":""},{"id":"inkjet","label":"Inkjet","sublabel":""},{"id":"thermal","label":"Thermal","sublabel":""},{"id":"impact","label":"Impact","sublabel":"Dot Matrix"}]}'), ('9', 'core1', 'match', 'Hardware', 'USB & High-Speed Interface Speeds', 'Match each interface standard to its maximum theoretical transfer speed. Click a standard on the left, then click the matching speed on the right.', 'USB 2.0 — 480 Mbps (High Speed). Still used for keyboards, mice, and low-bandwidth peripherals.
USB 3.2 Gen 1 — 5 Gbps (SuperSpeed). Formerly USB 3.0; the blue port standard.
USB 3.2 Gen 2 — 10 Gbps (SuperSpeed+). Formerly USB 3.1.
USB 3.2 Gen 2×2 — 20 Gbps. Requires USB-C; two 10 Gbps lanes bonded.
USB4 Gen 3×2 — 40 Gbps. Same speed as Thunderbolt 3/4; requires USB-C.
Thunderbolt 4 — 40 Gbps. USB-C connector; mandatory PCIe 4.0 tunneling, dual 4K.
Thunderbolt 5 — 120 Gbps burst / 80 Gbps base. USB-C; PCIe 5.0 tunneling.
SATA 3.0 — 6 Gbps. Standard connection for 2.5" SSDs and HDDs.', '{"left":[{"id":"usb2","label":"USB 2.0"},{"id":"usb31","label":"USB 3.2 Gen 1"},{"id":"usb32","label":"USB 3.2 Gen 2×2"},{"id":"usb4","label":"USB4 Gen 3×2"},{"id":"tb4","label":"Thunderbolt 4"},{"id":"tb5","label":"Thunderbolt 5"}],"right":[{"id":"usb2","label":"480 Mbps"},{"id":"usb31","label":"5 Gbps"},{"id":"usb32","label":"20 Gbps (USB-C only)"},{"id":"usb4","label":"40 Gbps (USB-C)"},{"id":"tb4","label":"40 Gbps (USB-C, PCIe 4.0)"},{"id":"tb5","label":"80–120 Gbps (USB-C, PCIe 5.0)"}]}'), ('1', 'core2', 'bucket', 'Security', 'Malware Classification', 'Classify each malware type or attack into the correct category. Click an item from the pool, then click the target category to place it.', 'Self-Replicating Malware spreads without user action (worms) or attaches to files needing user action to spread (viruses).
Deceptive Malware disguises itself as legitimate software (trojans) or provides remote unauthorized access (RATs).
Data-Stealing Malware captures keystrokes (keyloggers), monitors user behavior (spyware), or sells user data to advertisers (adware).
Destructive/Extortion Malware encrypts files for ransom (ransomware), hides itself at OS level (rootkits), or hijacks resources (cryptominer).
Network Attack Tools use infected machines for large-scale attacks (botnets/DDoS) or exploit unpatched network vulnerabilities (exploit kits).', '{"items":[{"id":"worm","label":"Worm","bucket":1},{"id":"virus","label":"Virus","bucket":1},{"id":"trojan","label":"Trojan","bucket":2},{"id":"rat","label":"RAT","bucket":2},{"id":"keylogger","label":"Keylogger","bucket":3},{"id":"spyware","label":"Spyware","bucket":3},{"id":"adware","label":"Adware","bucket":3},{"id":"ransomware","label":"Ransomware","bucket":4},{"id":"rootkit","label":"Rootkit","bucket":4},{"id":"cryptominer","label":"Cryptominer","bucket":4},{"id":"botnet","label":"Botnet / DDoS","bucket":5},{"id":"exploitkit","label":"Exploit Kit","bucket":5}],"buckets":[{"id":1,"label":"Self-Replicating","sublabel":"Spreads automatically"},{"id":2,"label":"Deceptive","sublabel":"Disguises itself"},{"id":3,"label":"Data-Stealing","sublabel":"Captures info"},{"id":4,"label":"Destructive / Extortion","sublabel":"Damages or ransoms"},{"id":5,"label":"Network Attack","sublabel":"Leverages infected machines"}]}'), ('2', 'core2', 'match', 'Security', 'Social Engineering Attacks', 'Match each social engineering attack type to its correct description. Click an attack on the left, then click the matching description on the right.', 'Phishing — mass email campaign impersonating trusted brands to steal credentials.
Spear Phishing — targeted phishing using personal details about the victim.
Whaling — spear phishing specifically targeting senior executives (CEO, CFO).
Vishing — voice/phone call pretending to be tech support, IRS, or bank.
Smishing — SMS text messages containing malicious links or false urgency.
Tailgating — physically following an authorized person through a secure door.
Shoulder Surfing — visually observing someone entering a password or PIN.
Dumpster Diving — retrieving sensitive documents or devices from trash.', '{"left":[{"id":"phish","label":"Phishing"},{"id":"spear","label":"Spear Phishing"},{"id":"whale","label":"Whaling"},{"id":"vish","label":"Vishing"},{"id":"smish","label":"Smishing"},{"id":"tailgate","label":"Tailgating"},{"id":"shoulder","label":"Shoulder Surfing"},{"id":"dumpster","label":"Dumpster Diving"}],"right":[{"id":"phish","label":"Mass fake email targeting anyone"},{"id":"spear","label":"Targeted email using victim''s personal details"},{"id":"whale","label":"Targeted email attack on C-level executives"},{"id":"vish","label":"Fraudulent phone call impersonating trusted org"},{"id":"smish","label":"Malicious SMS text message attack"},{"id":"tailgate","label":"Physically following someone through a secure door"},{"id":"shoulder","label":"Watching someone type credentials"},{"id":"dumpster","label":"Searching trash for sensitive data or hardware"}]}'), ('3', 'core2', 'bucket', 'Operating Systems', 'Windows Troubleshooting Tools', 'Classify each Windows tool into the correct category based on its primary purpose. Click an item from the pool, then click the target category.', 'System Repair Tools fix OS-level corruption and boot problems (SFC, DISM, CHKDSK, System Restore).
Process & Performance Tools monitor and manage running applications and resources (Task Manager, Resource Monitor, Performance Monitor).
Configuration & Settings Tools manage startup, services, and OS configuration (msconfig, regedit, Services.msc, MMC).
Network Diagnostic Tools analyze and troubleshoot network connectivity (ipconfig, netstat, ping, tracert, nslookup).
Event & Log Tools record and display system events, errors, and security audits (Event Viewer, Reliability Monitor).', '{"items":[{"id":"sfc","label":"SFC /scannow","bucket":1},{"id":"dism","label":"DISM","bucket":1},{"id":"chkdsk","label":"CHKDSK","bucket":1},{"id":"sysrestore","label":"System Restore","bucket":1},{"id":"taskmgr","label":"Task Manager","bucket":2},{"id":"resmon","label":"Resource Monitor","bucket":2},{"id":"perfmon","label":"Performance Monitor","bucket":2},{"id":"msconfig","label":"msconfig","bucket":3},{"id":"regedit","label":"regedit","bucket":3},{"id":"services","label":"Services.msc","bucket":3},{"id":"ipconfig","label":"ipconfig","bucket":4},{"id":"netstat","label":"netstat","bucket":4},{"id":"eventvwr","label":"Event Viewer","bucket":5},{"id":"relmon","label":"Reliability Monitor","bucket":5}],"buckets":[{"id":1,"label":"System Repair","sublabel":"Fix OS corruption"},{"id":2,"label":"Process & Performance","sublabel":"Monitor resources"},{"id":3,"label":"Configuration","sublabel":"Manage settings"},{"id":4,"label":"Network Diagnostics","sublabel":"Troubleshoot network"},{"id":5,"label":"Event & Logs","sublabel":"View system events"}]}'), ('4', 'core2', 'bucket', 'Security', 'Authentication Factor Types', 'Classify each authentication method into the correct MFA factor category. Click an item from the pool, then click the target category to place it.', 'Something you KNOW — knowledge-based factors: password, PIN, security question.
Something you HAVE — possession-based factors: smart card, hardware token (RSA), authenticator app (TOTP), SMS OTP.
Something you ARE — inherence/biometric factors: fingerprint, facial recognition, iris scan, voice recognition.
Somewhere you ARE — location-based factor: GPS location check, IP geolocation.', '{"items":[{"id":"password","label":"Password","bucket":"know"},{"id":"pin","label":"PIN","bucket":"know"},{"id":"secq","label":"Security Question","bucket":"know"},{"id":"smartcard","label":"Smart Card","bucket":"have"},{"id":"token","label":"Hardware Token (RSA)","bucket":"have"},{"id":"authapp","label":"Authenticator App (TOTP)","bucket":"have"},{"id":"smsotp","label":"SMS One-Time Password","bucket":"have"},{"id":"fingerprint","label":"Fingerprint Scan","bucket":"are"},{"id":"faceid","label":"Facial Recognition","bucket":"are"},{"id":"iris","label":"Iris Scan","bucket":"are"},{"id":"gps","label":"GPS Location Check","bucket":"where"}],"buckets":[{"id":"know","label":"Something you KNOW","sublabel":"Knowledge factor"},{"id":"have","label":"Something you HAVE","sublabel":"Possession factor"},{"id":"are","label":"Something you ARE","sublabel":"Biometric / inherence factor"},{"id":"where","label":"Somewhere you ARE","sublabel":"Location factor"}]}'), ('5', 'core2', 'match', 'Operating Systems', 'Windows Command-Line Tools', 'Match each Windows command to its primary function. Click a command on the left, then click the matching function on the right.', 'ipconfig — displays IP address, subnet mask, default gateway, and with /all shows MAC address and DNS servers.
netstat — shows active network connections, listening ports, and with -ano shows owning process IDs.
tasklist — lists all running processes with their PIDs and memory usage.
taskkill — terminates a process by PID (/PID) or name (/IM) — /F forces termination.
sfc /scannow — scans and repairs corrupted Windows system files using cached versions.
chkdsk /f /r — checks disk for file system errors (/f) and bad sectors (/r).
gpupdate /force — immediately applies Group Policy settings without waiting for refresh cycle.
diskpart — disk partitioning utility for creating, deleting, formatting, and assigning drives.', '{"left":[{"id":"ipconfig","label":"ipconfig /all"},{"id":"netstat","label":"netstat -ano"},{"id":"tasklist","label":"tasklist"},{"id":"sfc","label":"sfc /scannow"},{"id":"chkdsk","label":"chkdsk /f /r"},{"id":"gpupdate","label":"gpupdate /force"}],"right":[{"id":"ipconfig","label":"Show IP, MAC, DNS, and DHCP info"},{"id":"netstat","label":"Show open ports and process IDs"},{"id":"tasklist","label":"List all running processes and PIDs"},{"id":"sfc","label":"Scan and repair Windows system files"},{"id":"chkdsk","label":"Check disk for errors and bad sectors"},{"id":"gpupdate","label":"Force immediate Group Policy update"}]}'), ('6', 'core2', 'bucket', 'Operational Procedures', 'Backup Strategy Selection', 'Classify each characteristic into the correct backup strategy type. Click an item from the pool, then click the target category to place it.', 'Full backups copy everything and clear the archive bit on all files — largest backup, simplest restore.
Incremental copies only files changed since the last backup of ANY type, clears the archive bit — smallest daily backup but slowest restore (needs full + every incremental).
Differential copies all changes since the last FULL backup only, does NOT clear the archive bit — grows daily but faster restore (needs only full + latest differential).
Synthetic Full assembles a new full backup from existing full + incrementals on the backup server — no load on production systems.', '{"items":[{"id":"full1","label":"Copies ALL data regardless of changes","bucket":"full"},{"id":"full2","label":"Clears the archive bit on ALL files","bucket":"full"},{"id":"inc1","label":"Copies only files changed since the last backup of ANY type","bucket":"inc"},{"id":"inc2","label":"Clears the archive bit on changed files only","bucket":"inc"},{"id":"inc3","label":"Fastest daily backup — minimum storage per session","bucket":"inc"},{"id":"inc4","label":"Slowest restore — requires full + every incremental","bucket":"inc"},{"id":"diff1","label":"Copies all changes since the last FULL backup only","bucket":"diff"},{"id":"diff2","label":"Does NOT clear the archive bit","bucket":"diff"},{"id":"diff3","label":"Grows larger each day until the next full backup","bucket":"diff"},{"id":"diff4","label":"Fast restore — needs only last full + latest differential","bucket":"diff"},{"id":"synth1","label":"Assembled from existing full + incrementals on backup server","bucket":"synth"},{"id":"synth2","label":"No load on the production system during assembly","bucket":"synth"}],"buckets":[{"id":"full","label":"Full Backup","sublabel":""},{"id":"inc","label":"Incremental Backup","sublabel":""},{"id":"diff","label":"Differential Backup","sublabel":""},{"id":"synth","label":"Synthetic Full","sublabel":""}]}'), ('7', 'core2', 'match', 'Operating Systems', 'File System Comparison', 'Match each file system to its key characteristic. Click a file system on the left, then click the matching description on the right.', 'NTFS is the Windows default — supports permissions, EFS encryption, journaling, and files up to 16 TB.
FAT32 is universally compatible but limited to 4 GB per file — used on older flash drives and game consoles.
exFAT removes the 4 GB file size limit — ideal for large files on USB drives and SD cards, no journaling.
ext4 is the default Linux file system — journaling, large file support, backward compatible with ext2/ext3.
APFS is the macOS default since 10.13 — native encryption, snapshots, optimized for SSDs.
ReFS is the Windows Server self-healing file system — integrity checksums, no 2 TB partition limit.', '{"left":[{"id":"ntfs","label":"NTFS"},{"id":"fat32","label":"FAT32"},{"id":"exfat","label":"exFAT"},{"id":"ext4","label":"ext4"},{"id":"apfs","label":"APFS"},{"id":"refs","label":"ReFS"}],"right":[{"id":"ntfs","label":"Windows default — permissions, EFS encryption, journaling, files up to 16 TB"},{"id":"fat32","label":"Max 4 GB per file — universal compatibility with older devices and consoles"},{"id":"exfat","label":"No file size limit — large files on flash drives and SD cards, no journaling"},{"id":"ext4","label":"Default Linux file system — journaling, large file support, ext2/ext3 compatible"},{"id":"apfs","label":"macOS default (10.13+) — native encryption, snapshots, optimized for SSDs"},{"id":"refs","label":"Windows Server self-healing file system — checksums, no 2 TB partition limit"}]}'), ('8', 'core2', 'bucket', 'Security', 'Security Control Types', 'Classify each security control into the correct control type. Click an item from the pool, then click the target category to place it.', 'Physical controls restrict physical access to facilities and equipment.
Technical (logical) controls are implemented in hardware or software to enforce security policies.
Administrative controls are policies, procedures, and training that govern how people behave.
Detective controls identify and record security incidents after or as they occur.', '{"items":[{"id":"mantrap","label":"Mantrap / access control vestibule","bucket":"physical"},{"id":"cablelock","label":"Cable lock on a laptop","bucket":"physical"},{"id":"bollards","label":"Bollards (vehicle barriers)","bucket":"physical"},{"id":"guard","label":"Security guard","bucket":"physical"},{"id":"firewall","label":"Firewall rules","bucket":"technical"},{"id":"bitlocker","label":"Encryption (BitLocker)","bucket":"technical"},{"id":"lockout","label":"Account lockout policy","bucket":"technical"},{"id":"mfa","label":"MFA requirement","bucket":"technical"},{"id":"aup","label":"Acceptable Use Policy (AUP)","bucket":"admin"},{"id":"training","label":"Security awareness training","bucket":"admin"},{"id":"bgcheck","label":"Background checks for new hires","bucket":"admin"},{"id":"siem","label":"Audit logs / SIEM alerts","bucket":"detective"},{"id":"ids","label":"IDS (Intrusion Detection System)","bucket":"detective"},{"id":"cctv","label":"CCTV (Closed-Circuit TV)","bucket":"detective"}],"buckets":[{"id":"physical","label":"Physical","sublabel":"Restricts physical access"},{"id":"technical","label":"Technical","sublabel":"Hardware / software enforcement"},{"id":"admin","label":"Administrative","sublabel":"Policies & procedures"},{"id":"detective","label":"Detective","sublabel":"Identifies incidents"}]}'), ('9', 'core2', 'match', 'Operational Procedures', 'Remote Access Technologies', 'Match each remote access technology to its correct description. Click a technology on the left, then click the matching description on the right.', 'RDP (Remote Desktop Protocol) — Microsoft''s graphical remote desktop, TCP port 3389, requires Windows Pro or higher.
SSH (Secure Shell) — encrypted CLI remote access, TCP port 22, used for Linux/Unix and network device management.
VNC — cross-platform graphical remote access, less secure by default, should be tunneled through VPN or SSH.
VPN — encrypted tunnel to the corporate network, grants access to internal resources as if on-site.
TeamViewer / Quick Assist — invitation-based support tool, traverses firewalls without port forwarding.
RMM — IT platform for remotely monitoring, patching, and managing multiple endpoints simultaneously.', '{"left":[{"id":"rdp","label":"RDP"},{"id":"ssh","label":"SSH"},{"id":"vnc","label":"VNC"},{"id":"vpn","label":"VPN"},{"id":"tv","label":"TeamViewer / Quick Assist"},{"id":"rmm","label":"RMM"}],"right":[{"id":"rdp","label":"Graphical remote desktop — TCP port 3389, Windows Pro or higher"},{"id":"ssh","label":"Encrypted CLI remote access — TCP port 22, Linux/Unix/network devices"},{"id":"vnc","label":"Cross-platform graphical access — less secure, tunnel through VPN/SSH"},{"id":"vpn","label":"Encrypted tunnel to corporate network — access internal resources remotely"},{"id":"tv","label":"Invitation-based support tool — traverses firewalls, no port forwarding needed"},{"id":"rmm","label":"IT platform for monitoring, patching, and managing multiple endpoints"}]}'), ('201', 'netplus', 'bucket', '1.0 Networking Concepts', 'OSI Model — Protocol Classification', 'Classify each protocol or device into its correct OSI model layer. Click an item from the pool, then click the target layer to place it.', 'Layer 7 (Application) — user-facing protocols: HTTP, HTTPS, FTP, SMTP, DNS, SNMP, DHCP, Telnet, SSH.
Layer 6 (Presentation) — data format, encryption, compression: SSL/TLS, JPEG, ASCII.
Layer 5 (Session) — session setup/teardown: NetBIOS, RPC, SIP.
Layer 4 (Transport) — end-to-end delivery with port numbers: TCP (reliable), UDP (best-effort).
Layer 3 (Network) — logical addressing and routing: IP, ICMP, OSPF, BGP, Router.
Layer 2 (Data Link) — MAC addressing, framing, error detection: Ethernet, ARP, Switch, 802.11.
Layer 1 (Physical) — bits and signals: Hub, Repeater, NIC, copper/fiber cable.', '{"items":[{"id":"https","label":"HTTP / HTTPS","bucket":7},{"id":"smtp","label":"SMTP / IMAP / POP3","bucket":7},{"id":"dns","label":"DNS","bucket":7},{"id":"ssh","label":"SSH / Telnet","bucket":7},{"id":"tls","label":"SSL / TLS","bucket":6},{"id":"sip","label":"SIP / NetBIOS","bucket":5},{"id":"tcp","label":"TCP","bucket":4},{"id":"udp","label":"UDP","bucket":4},{"id":"ip","label":"IPv4 / IPv6","bucket":3},{"id":"icmp","label":"ICMP","bucket":3},{"id":"router","label":"Router","bucket":3},{"id":"arp","label":"ARP","bucket":2},{"id":"switch","label":"Switch / 802.11","bucket":2},{"id":"ethernet","label":"Ethernet Frame","bucket":2},{"id":"hub","label":"Hub / Repeater","bucket":1},{"id":"cable","label":"Copper / Fiber","bucket":1}],"buckets":[{"id":7,"label":"Layer 7","sublabel":"Application"},{"id":6,"label":"Layer 6","sublabel":"Presentation"},{"id":5,"label":"Layer 5","sublabel":"Session"},{"id":4,"label":"Layer 4","sublabel":"Transport"},{"id":3,"label":"Layer 3","sublabel":"Network"},{"id":2,"label":"Layer 2","sublabel":"Data Link"},{"id":1,"label":"Layer 1","sublabel":"Physical"}]}'), ('202', 'netplus', 'match', '1.0 Networking Concepts', 'IPv4 Address Classes', 'Match each IPv4 address class to its default subnet mask and typical use. Click a class on the left, then click its description on the right.', 'Class A — /8 (255.0.0.0): 1.0.0.0–126.255.255.255, 16 million hosts per network, used by very large organizations.
Class B — /16 (255.255.0.0): 128.0.0.0–191.255.255.255, 65,534 hosts per network, medium/large orgs.
Class C — /24 (255.255.255.0): 192.0.0.0–223.255.255.255, 254 hosts per network, small networks.
Class D — 224.0.0.0–239.255.255.255: reserved for multicast groups, no subnet mask.
Class E — 240.0.0.0–255.255.255.255: reserved for research/experimental use.', '{"left":[{"id":"classA","label":"Class A"},{"id":"classB","label":"Class B"},{"id":"classC","label":"Class C"},{"id":"classD","label":"Class D"},{"id":"classE","label":"Class E"}],"right":[{"id":"classA","label":"/8 — 1.x.x.x to 126.x.x.x — Very large networks"},{"id":"classB","label":"/16 — 128.x.x.x to 191.x.x.x — Medium/large networks"},{"id":"classC","label":"/24 — 192.x.x.x to 223.x.x.x — Small networks"},{"id":"classD","label":"224–239.x.x.x — Multicast (no subnet mask)"},{"id":"classE","label":"240–255.x.x.x — Reserved / Experimental"}]}'), ('203', 'netplus', 'bucket', '1.0 Networking Concepts', 'TCP vs UDP — Protocol Classification', 'Classify each protocol as TCP, UDP, or TCP/UDP. Click an item from the pool, then click the correct bucket.', 'TCP (reliable, connection-oriented): HTTP/HTTPS (80/443), FTP (20/21), SSH (22), Telnet (23), SMTP (25), POP3 (110), IMAP (143), RDP (3389), BGP (179).
UDP (fast, connectionless): DHCP (67/68), TFTP (69), NTP (123), SNMP (161/162), Syslog (514).
TCP/UDP (uses both): DNS (53), LDAP (389), SIP (5060).', '{"items":[{"id":"http","label":"HTTP (80)","bucket":"tcp"},{"id":"https","label":"HTTPS (443)","bucket":"tcp"},{"id":"ssh","label":"SSH (22)","bucket":"tcp"},{"id":"smtp","label":"SMTP (25)","bucket":"tcp"},{"id":"rdp","label":"RDP (3389)","bucket":"tcp"},{"id":"bgp","label":"BGP (179)","bucket":"tcp"},{"id":"dhcp","label":"DHCP (67/68)","bucket":"udp"},{"id":"tftp","label":"TFTP (69)","bucket":"udp"},{"id":"ntp","label":"NTP (123)","bucket":"udp"},{"id":"snmp","label":"SNMP (161)","bucket":"udp"},{"id":"syslog","label":"Syslog (514)","bucket":"udp"},{"id":"dns","label":"DNS (53)","bucket":"tcpudp"},{"id":"ldap","label":"LDAP (389)","bucket":"tcpudp"},{"id":"sip","label":"SIP (5060)","bucket":"tcpudp"}],"buckets":[{"id":"tcp","label":"TCP","sublabel":"Reliable / Connection-Oriented"},{"id":"udp","label":"UDP","sublabel":"Fast / Connectionless"},{"id":"tcpudp","label":"TCP/UDP","sublabel":"Uses Both"}]}'), ('204', 'netplus', 'order', '5.0 Network Troubleshooting', 'Network Troubleshooting Methodology', 'Arrange the CompTIA troubleshooting methodology steps in the correct order from first to last.', '1. Identify the problem — gather information, question users, identify symptoms, duplicate if possible, check for changes.
2. Establish a theory of probable cause — consider multiple approaches (OSI bottom-up, top-down, divide-and-conquer).
3. Test the theory to determine the cause — confirm or eliminate; if not confirmed, re-establish a new theory.
4. Establish a plan of action — resolve the problem with minimal impact on the environment.
5. Implement the solution or escalate — make the fix or pass to the appropriate team.
6. Verify full system functionality — confirm the fix and prevent recurrence.
7. Document findings, actions, and outcomes — record everything for future reference.', '{"items":[{"id":"identify","label":"Identify the problem"},{"id":"theory","label":"Establish a theory of probable cause"},{"id":"test","label":"Test the theory to determine cause"},{"id":"plan","label":"Establish a plan of action"},{"id":"implement","label":"Implement the solution or escalate"},{"id":"verify","label":"Verify full system functionality"},{"id":"document","label":"Document findings, actions, and outcomes"}]}'), ('205', 'netplus', 'match', '2.0 Network Implementation', 'Wireless 802.11 Standards', 'Match each 802.11 wireless standard to its maximum speed and primary frequency band.', '802.11a — 54 Mbps, 5 GHz only (less interference, shorter range).
802.11b — 11 Mbps, 2.4 GHz (earliest consumer standard).
802.11g — 54 Mbps, 2.4 GHz (backward compatible with b).
802.11n (Wi-Fi 4) — 600 Mbps, 2.4/5 GHz, introduced MIMO.
802.11ac (Wi-Fi 5) — 3.5 Gbps, 5 GHz, MU-MIMO, beamforming.
802.11ax (Wi-Fi 6/6E) — 9.6 Gbps, 2.4/5/6 GHz, OFDMA for dense environments.', '{"left":[{"id":"a","label":"802.11a"},{"id":"b","label":"802.11b"},{"id":"g","label":"802.11g"},{"id":"n","label":"802.11n (Wi-Fi 4)"},{"id":"ac","label":"802.11ac (Wi-Fi 5)"},{"id":"ax","label":"802.11ax (Wi-Fi 6)"}],"right":[{"id":"a","label":"54 Mbps · 5 GHz only"},{"id":"b","label":"11 Mbps · 2.4 GHz"},{"id":"g","label":"54 Mbps · 2.4 GHz"},{"id":"n","label":"600 Mbps · 2.4 / 5 GHz · MIMO"},{"id":"ac","label":"3.5 Gbps · 5 GHz · MU-MIMO"},{"id":"ax","label":"9.6 Gbps · 2.4 / 5 / 6 GHz · OFDMA"}]}'), ('206', 'netplus', 'bucket', '4.0 Network Security', 'Security Threat Classification', 'Classify each attack or threat into the correct category. Click an item from the pool, then click the target bucket.', 'On-path (MITM) attacks — attacker intercepts traffic between two parties: ARP poisoning, DNS spoofing, SSL stripping.
Denial of Service — overwhelm a target to make it unavailable: SYN flood, ping flood, DDoS.
Social Engineering — manipulate people rather than technology: phishing, vishing, pretexting.
Reconnaissance — gather information before attacking: port scanning (nmap), ping sweep, packet sniffing.', '{"items":[{"id":"arp","label":"ARP Poisoning","bucket":"onpath"},{"id":"dns-sp","label":"DNS Spoofing","bucket":"onpath"},{"id":"ssl-strip","label":"SSL Stripping","bucket":"onpath"},{"id":"syn","label":"SYN Flood","bucket":"dos"},{"id":"ddos","label":"DDoS Attack","bucket":"dos"},{"id":"ping-flood","label":"Ping Flood","bucket":"dos"},{"id":"phish","label":"Phishing Email","bucket":"social"},{"id":"vish","label":"Vishing (Voice)","bucket":"social"},{"id":"pretext","label":"Pretexting","bucket":"social"},{"id":"portscan","label":"Port Scanning","bucket":"recon"},{"id":"pingsweep","label":"Ping Sweep","bucket":"recon"},{"id":"sniff","label":"Packet Sniffing","bucket":"recon"}],"buckets":[{"id":"onpath","label":"On-Path / MITM","sublabel":"Interception"},{"id":"dos","label":"Denial of Service","sublabel":"Availability Attack"},{"id":"social","label":"Social Engineering","sublabel":"People-Based"},{"id":"recon","label":"Reconnaissance","sublabel":"Information Gathering"}]}'), ('207', 'netplus', 'match', '3.0 Network Operations', 'High Availability Metrics', 'Match each high-availability or disaster-recovery term to its correct definition.', 'RTO (Recovery Time Objective) — maximum acceptable time a system can be down after a failure.
RPO (Recovery Point Objective) — maximum acceptable amount of data loss measured in time.
MTBF (Mean Time Between Failures) — average time a device operates between failures; higher = more reliable.
MTTR (Mean Time To Repair) — average time to restore a failed component; lower = faster recovery.
SLA (Service Level Agreement) — contractual guarantee of uptime/performance between provider and customer.', '{"left":[{"id":"rto","label":"RTO"},{"id":"rpo","label":"RPO"},{"id":"mtbf","label":"MTBF"},{"id":"mttr","label":"MTTR"},{"id":"sla","label":"SLA"}],"right":[{"id":"rto","label":"Max acceptable downtime after a failure"},{"id":"rpo","label":"Max acceptable data loss measured in time"},{"id":"mtbf","label":"Average time between failures (higher = better)"},{"id":"mttr","label":"Average time to restore a failed system (lower = better)"},{"id":"sla","label":"Contractual uptime/performance guarantee"}]}'), ('208', 'netplus', 'order', '4.0 Network Security', 'DHCP IP Address Assignment Process', 'Arrange the DORA DHCP process steps in the correct order (client requesting a new IP address).', '1. Discover — client broadcasts DHCPDISCOVER to find available DHCP servers (UDP 68 → 67).
2. Offer — DHCP server responds with DHCPOFFER containing an available IP, subnet mask, gateway, and lease time.
3. Request — client broadcasts DHCPREQUEST accepting the offer (still broadcast so other servers know).
4. Acknowledge — server sends DHCPACK confirming the lease. Client can now use the IP address.
Remember the mnemonic: DORA — Discover, Offer, Request, Acknowledge.', '{"items":[{"id":"discover","label":"DHCPDISCOVER — Client broadcasts to find servers"},{"id":"offer","label":"DHCPOFFER — Server offers an available IP"},{"id":"request","label":"DHCPREQUEST — Client accepts the offer"},{"id":"ack","label":"DHCPACK — Server confirms the lease"}]}'), ('209', 'netplus', 'bucket', '2.0 Network Implementation', 'Cable Type Classification', 'Classify each cable or connector type into its correct category. Click an item from the pool, then click the target bucket.', 'Copper (twisted pair) — UTP/STP Ethernet cables (Cat5e, Cat6, Cat6a) transmit electrical signals over copper. Max distance ~100 m.
Fiber optic — uses light pulses; immune to EMI; longer distances (SMF: km, MMF: ~550 m). Connectors: LC, SC, ST, MT-RJ.
Coaxial — used for cable TV and broadband internet. RG-6 is standard for DOCSIS.
Transceivers/Modules — SFP, QSFP, SFP+ are hot-swappable modules connecting fiber to switching hardware.', '{"items":[{"id":"cat6","label":"Cat6 UTP","bucket":"copper"},{"id":"cat6a","label":"Cat6a STP","bucket":"copper"},{"id":"rj45","label":"RJ-45","bucket":"copper"},{"id":"smf","label":"Single-Mode Fiber","bucket":"fiber"},{"id":"mmf","label":"Multi-Mode Fiber","bucket":"fiber"},{"id":"lc","label":"LC Connector","bucket":"fiber"},{"id":"sc","label":"SC Connector","bucket":"fiber"},{"id":"rg6","label":"RG-6 Coax","bucket":"coax"},{"id":"bnc","label":"BNC Connector","bucket":"coax"},{"id":"sfp","label":"SFP Module","bucket":"module"},{"id":"qsfp","label":"QSFP Module","bucket":"module"}],"buckets":[{"id":"copper","label":"Copper / Twisted Pair","sublabel":"Electrical"},{"id":"fiber","label":"Fiber Optic","sublabel":"Light-based"},{"id":"coax","label":"Coaxial","sublabel":"TV / Broadband"},{"id":"module","label":"Transceivers","sublabel":"SFP / QSFP"}]}'), ('210', 'netplus', 'match', '4.0 Network Security', 'VPN Protocol Comparison', 'Match each VPN protocol to its key characteristic or use case.', 'PPTP — Point-to-Point Tunneling Protocol; oldest VPN protocol; port 1723; considered insecure (weak encryption).
L2TP/IPSec — Layer 2 Tunneling Protocol paired with IPSec for encryption; port 1701 (UDP); more secure than PPTP.
SSTP — Secure Socket Tunneling Protocol; uses SSL/TLS (port 443); bypasses most firewalls; Windows-native.
IKEv2/IPSec — fast re-establishment after interruption (MOBIKE); good for mobile devices; port 500/4500.
OpenVPN — open-source; highly configurable; uses SSL/TLS; ports 1194 UDP or 443 TCP.
WireGuard — modern, minimal codebase; very fast; UDP only; default port 51820.', '{"left":[{"id":"pptp","label":"PPTP"},{"id":"l2tp","label":"L2TP/IPSec"},{"id":"sstp","label":"SSTP"},{"id":"ikev2","label":"IKEv2/IPSec"},{"id":"openvpn","label":"OpenVPN"},{"id":"wg","label":"WireGuard"}],"right":[{"id":"pptp","label":"Port 1723 — Legacy, weak encryption"},{"id":"l2tp","label":"Port 1701 — L2 tunnel + IPSec encryption"},{"id":"sstp","label":"Port 443 SSL — Bypasses firewalls, Windows-native"},{"id":"ikev2","label":"Port 500/4500 — Best for mobile, fast reconnect"},{"id":"openvpn","label":"Port 1194/443 — Open-source, SSL/TLS-based"},{"id":"wg","label":"Port 51820 UDP — Modern, minimal, very fast"}]}'), ('osi-1', 'osi', 'bucket', '1.0 Networking Concepts', 'Protocols & Devices → OSI Layer', 'Classify each protocol, service, or device into its correct OSI layer. Click an item from the pool, then click the target layer.', 'Layer 7 (Application) — user-facing services: HTTP/S, FTP, SMTP, IMAP, POP3, DNS, DHCP, SNMP, NTP, SSH, Telnet, RDP, LDAP, TFTP.
Layer 6 (Presentation) — format, encryption, compression: SSL/TLS (encryption negotiation), JPEG, PNG, GIF, MPEG, ASCII, Unicode.
Layer 5 (Session) — open/maintain/close sessions: SIP (VoIP setup), NetBIOS, RPC, H.323.
Layer 4 (Transport) — end-to-end delivery with port numbers: TCP (reliable, connection-oriented), UDP (best-effort, connectionless).
Layer 3 (Network) — logical addressing and routing: IPv4, IPv6, ICMP, OSPF, EIGRP, BGP, RIP, Router, L3 Switch.
Layer 2 (Data Link) — MAC addressing and framing: Ethernet, ARP, 802.11 (Wi-Fi frames), L2 Switch, Bridge, STP, PPP.
Layer 1 (Physical) — raw bits and signals: Hub, Repeater, NIC (physical), copper/fiber/coax cable, Modem.', '{"items":[{"id":"http","label":"HTTP / HTTPS","bucket":7},{"id":"ftp","label":"FTP / SFTP","bucket":7},{"id":"smtp","label":"SMTP / IMAP / POP3","bucket":7},{"id":"dns","label":"DNS","bucket":7},{"id":"dhcp","label":"DHCP","bucket":7},{"id":"snmp","label":"SNMP","bucket":7},{"id":"rdp","label":"RDP","bucket":7},{"id":"tls","label":"SSL / TLS","bucket":6},{"id":"jpeg","label":"JPEG / PNG / GIF","bucket":6},{"id":"ascii","label":"ASCII / Unicode","bucket":6},{"id":"sip","label":"SIP","bucket":5},{"id":"netbios","label":"NetBIOS","bucket":5},{"id":"rpc","label":"RPC","bucket":5},{"id":"tcp","label":"TCP","bucket":4},{"id":"udp","label":"UDP","bucket":4},{"id":"ip","label":"IPv4 / IPv6","bucket":3},{"id":"icmp","label":"ICMP","bucket":3},{"id":"ospf","label":"OSPF","bucket":3},{"id":"router","label":"Router","bucket":3},{"id":"arp","label":"ARP","bucket":2},{"id":"ethernet","label":"Ethernet Frame","bucket":2},{"id":"8021q","label":"802.11 (Wi-Fi)","bucket":2},{"id":"switch","label":"L2 Switch","bucket":2},{"id":"hub","label":"Hub","bucket":1},{"id":"repeater","label":"Repeater","bucket":1},{"id":"cable","label":"Copper / Fiber Cable","bucket":1}],"buckets":[{"id":7,"label":"Layer 7","sublabel":"Application"},{"id":6,"label":"Layer 6","sublabel":"Presentation"},{"id":5,"label":"Layer 5","sublabel":"Session"},{"id":4,"label":"Layer 4","sublabel":"Transport"},{"id":3,"label":"Layer 3","sublabel":"Network"},{"id":2,"label":"Layer 2","sublabel":"Data Link"},{"id":1,"label":"Layer 1","sublabel":"Physical"}]}'), ('osi-2', 'osi', 'match', '1.0 Networking Concepts', 'Layer → PDU & Key Function', 'Match each OSI layer to its Protocol Data Unit (PDU) and primary function. Click a layer on the left, then its description on the right.', 'Layer 1 Physical — PDU: Bits. Converts data to electrical/optical/radio signals for transmission over the medium.
Layer 2 Data Link — PDU: Frames. Handles MAC addressing, framing, error detection (CRC/FCS), and access to the physical medium.
Layer 3 Network — PDU: Packets. Performs logical (IP) addressing and routing between different networks.
Layer 4 Transport — PDU: Segments (TCP) / Datagrams (UDP). Provides end-to-end delivery using port numbers; TCP is reliable, UDP is best-effort.
Layer 5 Session — PDU: Data. Establishes, maintains, and terminates sessions (logical connections) between applications.
Layer 6 Presentation — PDU: Data. Translates data formats, handles encryption/decryption and compression.
Layer 7 Application — PDU: Data. Provides network services directly to user applications (browsers, email clients, etc.).', '{"left":[{"id":"l1","label":"Layer 1 — Physical"},{"id":"l2","label":"Layer 2 — Data Link"},{"id":"l3","label":"Layer 3 — Network"},{"id":"l4","label":"Layer 4 — Transport"},{"id":"l5","label":"Layer 5 — Session"},{"id":"l6","label":"Layer 6 — Presentation"},{"id":"l7","label":"Layer 7 — Application"}],"right":[{"id":"l1","label":"PDU: Bits — transmits raw electrical/optical signals"},{"id":"l2","label":"PDU: Frames — MAC addressing, CRC error detection"},{"id":"l3","label":"PDU: Packets — IP addressing and routing"},{"id":"l4","label":"PDU: Segments/Datagrams — port numbers, end-to-end delivery"},{"id":"l5","label":"PDU: Data — session setup, maintenance, and teardown"},{"id":"l6","label":"PDU: Data — encryption, encoding, and compression"},{"id":"l7","label":"PDU: Data — user-facing services (HTTP, DNS, SMTP…)"}]}'), ('osi-3', 'osi', 'bucket', '1.0 Networking Concepts', 'Network Devices → OSI Layer', 'Classify each network device into the OSI layer where it primarily operates. Click an item, then click the correct layer.', 'Layer 1 (Physical): Hub (repeats signal to all ports), Repeater (extends signal), Modem (modulates/demodulates signal), NIC (physical interface), Access Point (RF radio is L1 — frames are L2).
Layer 2 (Data Link): L2 Switch (forwards based on MAC table), Bridge (divides collision domains), Wireless AP (802.11 frames).
Layer 3 (Network): Router (forwards packets based on IP routing table), Layer 3 / Multilayer Switch (routing + switching).
Layer 4 (Transport): Load Balancer (distributes connections by port/session), Stateful Firewall (tracks TCP/UDP sessions).
Layer 7 (Application): Application Firewall / WAF (inspects HTTP payload), Proxy Server (intermediary for application requests), IDS/IPS (deep packet inspection at application layer).', '{"items":[{"id":"hub","label":"Hub","bucket":1},{"id":"repeater","label":"Repeater","bucket":1},{"id":"modem","label":"Modem","bucket":1},{"id":"nic","label":"NIC (physical)","bucket":1},{"id":"l2sw","label":"L2 Switch","bucket":2},{"id":"bridge","label":"Bridge","bucket":2},{"id":"wap","label":"Wireless AP","bucket":2},{"id":"router","label":"Router","bucket":3},{"id":"l3sw","label":"L3 / Multilayer Switch","bucket":3},{"id":"lb","label":"Load Balancer","bucket":4},{"id":"fw-stat","label":"Stateful Firewall","bucket":4},{"id":"waf","label":"WAF / App Firewall","bucket":7},{"id":"proxy","label":"Proxy Server","bucket":7},{"id":"ids","label":"IDS / IPS (inline)","bucket":7}],"buckets":[{"id":1,"label":"Layer 1","sublabel":"Physical"},{"id":2,"label":"Layer 2","sublabel":"Data Link"},{"id":3,"label":"Layer 3","sublabel":"Network"},{"id":4,"label":"Layer 4","sublabel":"Transport"},{"id":7,"label":"Layer 7","sublabel":"Application"}]}'), ('osi-4', 'osi', 'match', '1.0 Networking Concepts', 'OSI vs TCP/IP Model Mapping', 'Match each TCP/IP model layer to its equivalent OSI layer(s). Click a TCP/IP layer on the left, then the OSI equivalent on the right.', 'TCP/IP Application Layer → combines OSI Layers 5, 6, and 7 (Session, Presentation, Application). Handles everything from session management to user-facing services.
TCP/IP Transport Layer → maps directly to OSI Layer 4 (Transport). TCP and UDP live here.
TCP/IP Internet Layer → maps to OSI Layer 3 (Network). IP, ICMP, and routing protocols operate here.
TCP/IP Network Access Layer (Link Layer) → combines OSI Layers 1 and 2 (Physical + Data Link). Covers both hardware signaling and MAC framing.', '{"left":[{"id":"app","label":"TCP/IP — Application Layer"},{"id":"trans","label":"TCP/IP — Transport Layer"},{"id":"inet","label":"TCP/IP — Internet Layer"},{"id":"netacc","label":"TCP/IP — Network Access Layer"}],"right":[{"id":"app","label":"OSI Layers 5 + 6 + 7 (Session, Presentation, Application)"},{"id":"trans","label":"OSI Layer 4 (Transport) — TCP / UDP"},{"id":"inet","label":"OSI Layer 3 (Network) — IP / ICMP / Routing"},{"id":"netacc","label":"OSI Layers 1 + 2 (Physical + Data Link)"}]}'), ('osi-5', 'osi', 'bucket', '5.0 Network Troubleshooting', 'Troubleshooting Symptoms → OSI Layer', 'A technician uses the OSI bottom-up model to troubleshoot. Classify each symptom into the OSI layer most likely responsible.', 'Layer 1 (Physical) — symptoms involving physical media or signal: no link light, damaged cable, low signal strength, interface in ''down/down'' state.
Layer 2 (Data Link) — symptoms involving MAC/framing: high CRC/FCS error count, duplicate MAC address, VLAN mismatch, STP loop, missing ARP entry.
Layer 3 (Network) — symptoms involving IP addressing or routing: wrong subnet mask, ''Destination Host Unreachable'', routing loop, incorrect default gateway.
Layer 4 (Transport) — symptoms involving ports and sessions: port blocked by firewall, TCP three-way handshake never completes, connection reset (RST), service not listening on expected port.
Layer 5–7 (Upper Layers) — symptoms involving applications or security: HTTP 404/500 errors, SSL/TLS certificate error, authentication failure, DNS name not resolving, application timeout despite ping working.', '{"items":[{"id":"no-link","label":"No link light on NIC","bucket":"l1"},{"id":"cut-cable","label":"Cut / damaged cable","bucket":"l1"},{"id":"attenuation","label":"Signal attenuation / weak Wi-Fi","bucket":"l1"},{"id":"crc","label":"High CRC / FCS error count","bucket":"l2"},{"id":"dup-mac","label":"Duplicate MAC address conflict","bucket":"l2"},{"id":"vlan-mis","label":"VLAN mismatch on trunk port","bucket":"l2"},{"id":"stp-loop","label":"Switching loop / broadcast storm","bucket":"l2"},{"id":"wrong-ip","label":"Incorrect IP / subnet mask","bucket":"l3"},{"id":"no-gw","label":"Cannot reach default gateway","bucket":"l3"},{"id":"rt-loop","label":"Routing loop (TTL exceeded)","bucket":"l3"},{"id":"port-block","label":"Port blocked by firewall rule","bucket":"l4"},{"id":"rst","label":"TCP connection reset (RST flag)","bucket":"l4"},{"id":"no-listen","label":"Service not listening on port","bucket":"l4"},{"id":"http404","label":"HTTP 404 / 500 error","bucket":"l57"},{"id":"cert-err","label":"SSL/TLS certificate error","bucket":"l57"},{"id":"auth-fail","label":"Authentication failure","bucket":"l57"},{"id":"dns-fail","label":"DNS name not resolving","bucket":"l57"}],"buckets":[{"id":"l1","label":"Layer 1","sublabel":"Physical"},{"id":"l2","label":"Layer 2","sublabel":"Data Link"},{"id":"l3","label":"Layer 3","sublabel":"Network"},{"id":"l4","label":"Layer 4","sublabel":"Transport"},{"id":"l57","label":"Layers 5–7","sublabel":"Upper Layers"}]}'), ('osi-6', 'osi', 'order', '1.0 Networking Concepts', 'Encapsulation — Sender Process', 'Arrange the encapsulation steps in the correct order as data travels from the sending application down to the physical wire. Drag items to reorder.', 'Encapsulation is the process of adding headers (and trailers) as data moves down the OSI stack before transmission.

1. Application (L7) — application generates user data (e.g., an HTTP request).
2. Presentation (L6) — data is formatted, encrypted, and/or compressed (e.g., TLS wrapping).
3. Session (L5) — a session token/identifier is attached to manage the dialog.
4. Transport (L4) — TCP/UDP header added (source/destination ports, sequence number) → becomes a Segment or Datagram.
5. Network (L3) — IP header added (source/destination IP addresses) → becomes a Packet.
6. Data Link (L2) — MAC header + FCS trailer added → becomes a Frame.
7. Physical (L1) — frame is converted to bits and transmitted as electrical/optical/RF signals.', '{"items":[{"id":"app","label":"Application (L7) — generates user data"},{"id":"pres","label":"Presentation (L6) — encrypts / formats data"},{"id":"sess","label":"Session (L5) — attaches session identifier"},{"id":"trans","label":"Transport (L4) — adds TCP/UDP header → Segment/Datagram"},{"id":"net","label":"Network (L3) — adds IP header → Packet"},{"id":"dl","label":"Data Link (L2) — adds MAC header + FCS → Frame"},{"id":"phys","label":"Physical (L1) — converts to bits and transmits"}]}'), ('osi-7', 'osi', 'match', '1.0 Networking Concepts', 'Key Characteristic → OSI Layer', 'Match each defining characteristic to the OSI layer it best describes. Click a characteristic on the left, then the layer on the right.', 'Physical (L1) — concerned with bits and the physical medium (voltage levels, pin-outs, cable types, signal timing).
Data Link (L2) — uses MAC (hardware) addresses to deliver frames within a local network segment; handles error detection via CRC/FCS.
Network (L3) — uses logical IP addresses to route packets across multiple networks (inter-network delivery).
Transport (L4) — uses port numbers to multiplex multiple services on one IP address; TCP provides reliability via acknowledgments and retransmission.
Session (L5) — maintains full-duplex or half-duplex dialog; responsible for authentication and reconnection after interruption.
Presentation (L6) — ensures data is in a readable format; responsible for encryption (TLS), character encoding (ASCII/UTF-8), and compression.
Application (L7) — closest to the end user; provides the API/interface that applications use to send and receive data over the network.', '{"left":[{"id":"l1","label":"Uses voltage levels, pin-outs, and cable specifications to transmit raw bits"},{"id":"l2","label":"Forwards traffic based on 48-bit hardware (MAC) addresses within a LAN"},{"id":"l3","label":"Routes packets between networks using logical 32/128-bit IP addresses"},{"id":"l4","label":"Multiplexes services with port numbers; TCP adds reliability with ACKs"},{"id":"l5","label":"Controls dialog (full/half-duplex) and re-establishes sessions after disruption"},{"id":"l6","label":"Handles TLS encryption, ASCII/UTF-8 encoding, and JPEG compression"},{"id":"l7","label":"Provides the network interface for user applications such as browsers and email clients"}],"right":[{"id":"l1","label":"Physical (Layer 1)"},{"id":"l2","label":"Data Link (Layer 2)"},{"id":"l3","label":"Network (Layer 3)"},{"id":"l4","label":"Transport (Layer 4)"},{"id":"l5","label":"Session (Layer 5)"},{"id":"l6","label":"Presentation (Layer 6)"},{"id":"l7","label":"Application (Layer 7)"}]}'), ('osi-8', 'osi', 'bucket', '4.0 Network Security', 'Security Controls → OSI Layer', 'Classify each security mechanism or control into the OSI layer where it primarily operates.', 'Layer 1 (Physical): Physical access controls (locked server room, cable locks), disabling unused ports on a patch panel.
Layer 2 (Data Link): Port security (limit MACs per port), MAC filtering, 802.1X NAC (EAP over LAN), VLAN segmentation, Dynamic ARP Inspection (DAI).
Layer 3 (Network): ACLs on routers (filter by IP/subnet), IPSec (encrypts IP packets), DHCP snooping (validates IP-to-port binding), uRPF (anti-spoofing).
Layer 4 (Transport): Stateful firewall (tracks TCP/UDP sessions), port-based filtering, TCP SYN cookies (SYN flood mitigation).
Layer 7 (Application): WAF (inspects HTTP/S payloads), content filtering / URL filtering, DLP (deep packet inspection), antivirus proxy, TLS inspection.', '{"items":[{"id":"locked-room","label":"Locked server room","bucket":1},{"id":"cable-lock","label":"Cable locks on hardware","bucket":1},{"id":"port-sec","label":"Port security (MAC limit)","bucket":2},{"id":"8021x","label":"802.1X / NAC (EAP over LAN)","bucket":2},{"id":"dai","label":"Dynamic ARP Inspection (DAI)","bucket":2},{"id":"mac-filter","label":"MAC address filtering","bucket":2},{"id":"acl","label":"Router ACL (IP-based)","bucket":3},{"id":"ipsec","label":"IPSec","bucket":3},{"id":"dhcp-snoop","label":"DHCP Snooping","bucket":3},{"id":"stat-fw","label":"Stateful Firewall","bucket":4},{"id":"syn-cookie","label":"TCP SYN Cookies","bucket":4},{"id":"waf","label":"WAF (Web Application Firewall)","bucket":7},{"id":"url-filter","label":"URL / Content Filtering","bucket":7},{"id":"dlp","label":"DLP (Deep Packet Inspection)","bucket":7}],"buckets":[{"id":1,"label":"Layer 1","sublabel":"Physical"},{"id":2,"label":"Layer 2","sublabel":"Data Link"},{"id":3,"label":"Layer 3","sublabel":"Network"},{"id":4,"label":"Layer 4","sublabel":"Transport"},{"id":7,"label":"Layer 7","sublabel":"Application"}]}'), ('osi-9', 'osi', 'match', '1.0 Networking Concepts', 'Routing Protocol → Category', 'Match each routing protocol or concept to its correct category. All routing protocols operate at OSI Layer 3.', 'Interior Gateway Protocols (IGPs) are used within a single autonomous system (AS).
  Link-State IGPs: OSPF (Open Shortest Path First) and IS-IS build a complete topology map and use Dijkstra''s algorithm — fast convergence, scalable.
  Distance-Vector IGPs: RIP (Routing Information Protocol) shares full routing tables with neighbors; slow convergence, max 15 hops.
  Hybrid (Advanced Distance-Vector): EIGRP (Cisco-proprietary) uses DUAL algorithm — combines features of both link-state and distance-vector.

Exterior Gateway Protocols (EGPs) route between autonomous systems on the internet.
  BGP (Border Gateway Protocol) is the only EGP in use today — it is the ''protocol of the internet'' and uses path-vector routing.', '{"left":[{"id":"ospf","label":"OSPF"},{"id":"isis","label":"IS-IS"},{"id":"rip","label":"RIP"},{"id":"eigrp","label":"EIGRP"},{"id":"bgp","label":"BGP"}],"right":[{"id":"ospf","label":"IGP — Link-State (Dijkstra algorithm, fast convergence)"},{"id":"isis","label":"IGP — Link-State (used by ISPs, similar to OSPF)"},{"id":"rip","label":"IGP — Distance-Vector (hop count metric, max 15 hops)"},{"id":"eigrp","label":"IGP — Hybrid / Advanced Distance-Vector (Cisco, DUAL)"},{"id":"bgp","label":"EGP — Path-Vector (routes between autonomous systems)"}]}');